apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: schema-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Resource limits
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Timeout
        run.googleapis.com/timeout: "300s"
        # Service account (optional)
        # run.googleapis.com/service-account: schema-agent@YOUR_PROJECT_ID.iam.gserviceaccount.com
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: schema-agent
        image: gcr.io/YOUR_PROJECT_ID/schema-agent:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: ENABLE_AUTH
          value: "false"
        - name: ALLOWED_ORIGINS
          value: "*"
        - name: MAX_QUESTION_LENGTH
          value: "1000"
        # Optional: Use Cloud Storage for embeddings
        # - name: EMBEDDINGS_BUCKET
        #   value: "gs://your-bucket-name/embeddings"
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5