# AP Automation Program Configuration

program_type: ap_automation

dimensions:
  customer: "TechCorp Solutions"
  environment: sandbox
  customer_segment: mid_market_ap
  program_variant: integrated_ap_automation
  integration_type: quickbooks
  payment_method: virtual_cards

options:
  categories:
    - card_product
    - on_demand_funding
    - payment_cards
    - spend_rules
    - velocity_rules
    - collaborative_authorization_copy
    - transactions
    - reports
    
  flows:
    - standard_ap_automation_setup
    - comprehensive_spend_controls
    - payment_processing_flow
    - supplier_payment_management
    
  include_simulations: true
  enable_on_demand_funding: true