# Generate collection with solutions document
type: collection

config:
  program_type: commercial_prepaid
  
  dimensions:
    customer: "TechCorp Solutions"
    environment: production
    business_type: small_business
    program_variant: expense_management_prepaid
    
  options:
    categories:
      - business_account_holder
      - authorized_users
      - payment_cards
      - spend_rules
      - transactions
      
    flows:
      - standard_business_prepaid_onboarding
      - authorized_user_setup

# Generate both collection and solutions document
outputs:
  - collection
  - summary
  - solutions