# Example: Generate Postman collection with all outputs
type: collection

config:
  program_type: consumer_credit
  
  dimensions:
    customer: "ABC Bank"
    environment: production
    region: us-east
    risk_tier: prime
    
  options:
    # Categories to include
    categories:
      - person_account_holder
      - application
      - financial_accounts
      - payment_cards
      - transactions
      - spend_rules
      
    # Flows to document
    flows:
      - standard_onboarding
      - manual_review_process
      - physical_card_complete_lifecycle
      
    # Additional filtering
    include_simulations: false
    max_operations_per_category: 20

# What to generate
outputs:
  - collection      # Postman collection JSON
  - yaml           # Operations documentation YAML
  - summary        # Human-readable summary
  - test_data      # Sample test data