# Consumer Credit Card Program Configuration

program_type: consumer_credit

dimensions:
  customer: "First National Bank"
  environment: production
  customer_segment: retail
  program_variant: rewards_cashback
  risk_tier: prime
  card_type: both  # physical and virtual

options:
  categories:
    - person_account_holder
    - application
    - underwriting
    - financial_accounts
    - credit_limit
    - payment_cards
    - transactions
    - spend_rules
    - rewards_redemption
    
  flows:
    - standard_onboarding
    - manual_review_process
    - comprehensive_spend_controls
    - rewards_redemption_setup
    - physical_card_complete_lifecycle
    
  include_simulations: true
  include_adverse_actions: true
  include_delinquency_management: true