# Sample Configuration for YAML-based Generator
# This file defines what collection to generate

program_type: commercial_prepaid

dimensions:
  customer: "Test Bank"
  environment: sandbox
  business_type: small_business
  program_variant: expense_management_prepaid
  region: us_east

options:
  # Categories to include in the collection
  categories:
    - api_key_management
    - organization
    - business_account_holder
    - application
    - authorized_users
    - financial_accounts
    - payment_cards
    - transactions
    - spend_rules
    - velocity_rules
    - notification_targets
    
  # Operation flows to include
  flows:
    - standard_business_prepaid_onboarding
    - authorized_user_setup
    - comprehensive_spend_controls
    - ach_funding_setup
    
  # Additional options
  include_simulations: true
  include_webhooks: true
  max_operations_per_category: 10