# Complete E2E generation for Trip.com
type: collection
config:
  program_type: trip.com
  dimensions:
    customer: "Trip.com"
    environment: production
    integration: travel_platform
    region: global
    use_case: "Travel and Expense Management"
  options:
    # Use actual categories from the enhanced YAML
    categories:
      - payment_cards
      - card_product
      - financial_accounts
      - transactions
      - spend_rules
      - velocity_rules
      - collaborative_authorization
      - notification_targets
    flows:
      - standard_onboarding
      - card_issuance
    features:
      - virtual_cards
      - on_demand_funding
      - multi_currency
      - real_time_auth
      - spend_controls
      - webhook_notifications
      - collaborative_authorization
    # Configure solutions document sections
    solutions_sections:
      - header
      - executive_summary
      - table_of_contents
      - technical_overview
      - use_cases
      - implementation_flows
      - api_reference
      - integration_guide
      - security_compliance
      - appendices
outputs:
  - collection     # Postman collection
  - yaml          # Operations YAML
  - test_data     # Test data JSON
  - solutions     # Solutions document
  - summary       # Summary report