# Full asset generation configuration for Trip.com
type: collection
config:
  program_type: travel_services
  dimensions:
    customer: "Trip.com"
    environment: production
    integration: travel_platform
    region: global
  options:
    categories:
      - api_key_management
      - organization
      - card_product
      - financial_accounts
      - payment_cards
      - transactions
      - spend_rules
      - velocity_rules
      - collaborative_authorization
      - notification_targets
      - reports
    flows:
      - standard_onboarding
      - card_issuance
      - transaction_processing
    features:
      - virtual_cards
      - multi_currency
      - real_time_auth
      - spend_controls
      - webhook_notifications
outputs:
  - collection     # Postman collection
  - yaml          # Operations YAML
  - test_data     # Test data JSON
  - solutions     # Solutions document
  - summary       # Summary report